# Generated by Django 4.2.4 on 2023-08-17 07:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, db_column='ID', primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField(db_column='Provider_ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(verbose_name=django.db.models.fields.TextField), db_column='Messages', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_At')),
                ('user_id', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Conversations',
                'ordering': ['created_at'],
            },
        ),
    ]
