# Generated by Django 4.2.4 on 2023-08-17 08:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_created_at_alter_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(verbose_name=django.db.models.fields.TextField), null=True, size=None),
        ),
    ]
