# Generated by Django 4.2.4 on 2023-08-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_alter_conversation_provider_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='app_conversations',
        ),
    ]
