# Generated by Django 4.2.4 on 2023-08-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_conversation_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
    ]
